// Generated by https://quicktype.io

export interface User {
  email: string;
  createdAt: Date | string;
  id: number;
  updatedAt: Date | string;
  information: Information;
  users_address: UsersAddress;
  Photo: Photo;
}

export interface Photo {
  url: string;
  id: number;
}

export interface Information {
  id: number;
  name: string;
  lastName: string;
  dateOfBirth: null;
  createdAt: Date;
  updatedAt: Date;
  userId: number;
}

export interface UsersAddress {
  id: number;
  country: string;
  department: string;
  city: string;
  directions: string;
  createdAt: Date | string;
  updatedAt: Date | string;
  token: string;
}
